language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DucklingHTTPExtractor
- name: DIETClassifier
  epochs: 100
- name: ResponseSelector
  epochs: 100
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 3
  epochs: 100
- name: RulePolicy
