language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DucklingHTTPExtractor
- name: DIETClassifier
  epochs: 1
- name: ResponseSelector
  epochs: 2
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 3
  epochs: 2
- name: RulePolicy
